export const SIGNUP_WITH_GOOGLE = "SIGNUP_WITH_GOOGLE";
export const GET_USERS = "GET_USERS";

export const GET_PRODUCTS = "GET_PRODUCTS"
export const ADD_PRODUCTS = "ADD_PRODUCTS"
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS"
export const DELETE_PRODUCT = "DELETE_PRODUCT"

export const ADD_CART = "ADD_CART"
export const DELETE_CART = "DELETE_CART"
export const UPDATE_CART = "UPDATE_CART"